accounts:
  - name: alice
    coins: ['20000token', '200000000stake']
  - name: bob
    coins: ['10000token', '100000000stake']
  - name: relayer
    address: cosmos1m8f52vhw4twcj7gm98s7jq3xsje29zk83ewklv
    coins: ['20000token', '200000000stake']

validator:
  name: alice
  staked: '100000000stake'
client:
  vuex:
    path: 'vue/src/store'
  openapi:
    path: 'docs/static/openapi.yml'
genesis:
  chain_id: 'rosen:0'
faucet:
  host: ':4501'
  name: bob
  coins: ['5token', '100000stake']
host:
  rpc: ':26659'
  p2p: ':26658'
  prof: ':6061'
  grpc: ':9091'
  api: ':1318'
  frontend: ':8081'
  dev-ui: ':12346'
