// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibcbridge/packet.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type IbcbridgePacketData struct {
	// Types that are valid to be assigned to Packet:
	//	*IbcbridgePacketData_MintRequest
	Packet isIbcbridgePacketData_Packet `protobuf_oneof:"packet"`
}

func (m *IbcbridgePacketData) Reset()         { *m = IbcbridgePacketData{} }
func (m *IbcbridgePacketData) String() string { return proto.CompactTextString(m) }
func (*IbcbridgePacketData) ProtoMessage()    {}
func (*IbcbridgePacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9181d8e9e54bcaf, []int{0}
}
func (m *IbcbridgePacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcbridgePacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcbridgePacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcbridgePacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcbridgePacketData.Merge(m, src)
}
func (m *IbcbridgePacketData) XXX_Size() int {
	return m.Size()
}
func (m *IbcbridgePacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcbridgePacketData.DiscardUnknown(m)
}

var xxx_messageInfo_IbcbridgePacketData proto.InternalMessageInfo

type isIbcbridgePacketData_Packet interface {
	isIbcbridgePacketData_Packet()
	MarshalTo([]byte) (int, error)
	Size() int
}

type IbcbridgePacketData_MintRequest struct {
	MintRequest *MsgMintRequest `protobuf:"bytes,1,opt,name=mintRequest,proto3,oneof" json:"mintRequest,omitempty"`
}

func (*IbcbridgePacketData_MintRequest) isIbcbridgePacketData_Packet() {}

func (m *IbcbridgePacketData) GetPacket() isIbcbridgePacketData_Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (m *IbcbridgePacketData) GetMintRequest() *MsgMintRequest {
	if x, ok := m.GetPacket().(*IbcbridgePacketData_MintRequest); ok {
		return x.MintRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*IbcbridgePacketData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*IbcbridgePacketData_MintRequest)(nil),
	}
}

type MsgMintRequest struct {
	Reciever    string `protobuf:"bytes,1,opt,name=reciever,proto3" json:"reciever,omitempty"`
	Amount      uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee         uint64 `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
	SrcChainId  uint32 `protobuf:"varint,4,opt,name=src_chain_id,json=srcChainId,proto3" json:"src_chain_id,omitempty"`
	DestChainId uint32 `protobuf:"varint,5,opt,name=dest_chain_id,json=destChainId,proto3" json:"dest_chain_id,omitempty"`
}

func (m *MsgMintRequest) Reset()         { *m = MsgMintRequest{} }
func (m *MsgMintRequest) String() string { return proto.CompactTextString(m) }
func (*MsgMintRequest) ProtoMessage()    {}
func (*MsgMintRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9181d8e9e54bcaf, []int{1}
}
func (m *MsgMintRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMintRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMintRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMintRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintRequest.Merge(m, src)
}
func (m *MsgMintRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgMintRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintRequest proto.InternalMessageInfo

func (m *MsgMintRequest) GetReciever() string {
	if m != nil {
		return m.Reciever
	}
	return ""
}

func (m *MsgMintRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *MsgMintRequest) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *MsgMintRequest) GetSrcChainId() uint32 {
	if m != nil {
		return m.SrcChainId
	}
	return 0
}

func (m *MsgMintRequest) GetDestChainId() uint32 {
	if m != nil {
		return m.DestChainId
	}
	return 0
}

func init() {
	proto.RegisterType((*IbcbridgePacketData)(nil), "rosenlabs.rosenchain.ibcbridge.IbcbridgePacketData")
	proto.RegisterType((*MsgMintRequest)(nil), "rosenlabs.rosenchain.ibcbridge.MsgMintRequest")
}

func init() { proto.RegisterFile("ibcbridge/packet.proto", fileDescriptor_e9181d8e9e54bcaf) }

var fileDescriptor_e9181d8e9e54bcaf = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x63, 0x5a, 0xaa, 0xe2, 0x52, 0x84, 0x8c, 0x54, 0x45, 0x0c, 0x56, 0xd4, 0x29, 0x0b,
	0x8e, 0x54, 0xde, 0xa0, 0x30, 0x50, 0x89, 0x4a, 0xc8, 0x23, 0x4b, 0xe5, 0x38, 0x97, 0xd4, 0x82,
	0xfc, 0x60, 0x3b, 0x08, 0xde, 0x82, 0x07, 0xe0, 0x81, 0x18, 0x3b, 0x32, 0xa2, 0xe4, 0x45, 0x50,
	0x4c, 0x69, 0x60, 0x61, 0xbb, 0xe7, 0xe8, 0xbb, 0x3f, 0x3a, 0x17, 0x4f, 0x54, 0x2c, 0x63, 0xad,
	0x92, 0x14, 0xa2, 0x52, 0xc8, 0x7b, 0xb0, 0xac, 0xd4, 0x85, 0x2d, 0x08, 0xd5, 0x85, 0x81, 0xfc,
	0x41, 0xc4, 0x86, 0xb9, 0x4a, 0xae, 0x85, 0xca, 0xd9, 0x0e, 0x9e, 0x1a, 0x7c, 0xb2, 0xf8, 0x11,
	0x37, 0xae, 0xf1, 0x52, 0x58, 0x41, 0x38, 0x1e, 0x65, 0x2a, 0xb7, 0x1c, 0x1e, 0x2b, 0x30, 0xd6,
	0x47, 0x01, 0x0a, 0x47, 0x33, 0xc6, 0xfe, 0x1f, 0xc6, 0x96, 0x26, 0x5d, 0x76, 0x5d, 0x57, 0x1e,
	0xff, 0x3d, 0x64, 0x3e, 0xc4, 0x83, 0xef, 0xd3, 0xa6, 0x6f, 0x08, 0x1f, 0xfd, 0x65, 0xc9, 0x29,
	0x1e, 0x6a, 0x90, 0x0a, 0x9e, 0x40, 0xbb, 0x6d, 0x07, 0x7c, 0xa7, 0xc9, 0x04, 0x0f, 0x44, 0x56,
	0x54, 0xb9, 0xf5, 0xf7, 0x02, 0x14, 0xf6, 0xf9, 0x56, 0x91, 0x63, 0xdc, 0xbb, 0x03, 0xf0, 0x7b,
	0xce, 0x6c, 0x4b, 0x12, 0xe0, 0x43, 0xa3, 0xe5, 0xca, 0xdd, 0xb5, 0x52, 0x89, 0xdf, 0x0f, 0x50,
	0x38, 0xe6, 0xd8, 0x68, 0x79, 0xd1, 0x5a, 0x8b, 0x84, 0x4c, 0xf1, 0x38, 0x01, 0x63, 0x3b, 0x64,
	0xdf, 0x21, 0xa3, 0xd6, 0xdc, 0x32, 0xf3, 0xeb, 0xf7, 0x9a, 0xa2, 0x4d, 0x4d, 0xd1, 0x67, 0x4d,
	0xd1, 0x6b, 0x43, 0xbd, 0x4d, 0x43, 0xbd, 0x8f, 0x86, 0x7a, 0xb7, 0xb3, 0x54, 0xd9, 0x75, 0x15,
	0x33, 0x59, 0x64, 0x91, 0x4b, 0xe0, 0xac, 0x0d, 0x23, 0xea, 0xc2, 0x88, 0x9e, 0xa3, 0xee, 0x11,
	0xf6, 0xa5, 0x04, 0x13, 0x0f, 0xdc, 0x23, 0xce, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x69,
	0x1d, 0x6c, 0xa2, 0x01, 0x00, 0x00,
}

func (m *IbcbridgePacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcbridgePacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcbridgePacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Packet != nil {
		{
			size := m.Packet.Size()
			i -= size
			if _, err := m.Packet.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *IbcbridgePacketData_MintRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcbridgePacketData_MintRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.MintRequest != nil {
		{
			size, err := m.MintRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *MsgMintRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMintRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMintRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DestChainId != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.DestChainId))
		i--
		dAtA[i] = 0x28
	}
	if m.SrcChainId != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.SrcChainId))
		i--
		dAtA[i] = 0x20
	}
	if m.Fee != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.Fee))
		i--
		dAtA[i] = 0x18
	}
	if m.Amount != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Reciever) > 0 {
		i -= len(m.Reciever)
		copy(dAtA[i:], m.Reciever)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Reciever)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IbcbridgePacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Packet != nil {
		n += m.Packet.Size()
	}
	return n
}

func (m *IbcbridgePacketData_MintRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MintRequest != nil {
		l = m.MintRequest.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *MsgMintRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Reciever)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovPacket(uint64(m.Amount))
	}
	if m.Fee != 0 {
		n += 1 + sovPacket(uint64(m.Fee))
	}
	if m.SrcChainId != 0 {
		n += 1 + sovPacket(uint64(m.SrcChainId))
	}
	if m.DestChainId != 0 {
		n += 1 + sovPacket(uint64(m.DestChainId))
	}
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IbcbridgePacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcbridgePacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcbridgePacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &MsgMintRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &IbcbridgePacketData_MintRequest{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMintRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMintRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMintRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reciever", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reciever = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			m.Fee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Fee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcChainId", wireType)
			}
			m.SrcChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SrcChainId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestChainId", wireType)
			}
			m.DestChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestChainId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
